//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

// 
// 此源代码是由 Microsoft.VSDesigner 4.0.30319.42000 版自动生成。
// 
#pragma warning disable 1591

namespace Hands.K3.SCM.App.Core.JLCWebService {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2558.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="CustomerOpenServiceHttpBinding", Namespace="http://webservice.product.gordian.com")]
    public partial class CustomerOpenService : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback queryOrderDetailsByQcCodeOperationCompleted;
        
        private System.Threading.SendOrPostCallback queryOrderInfoByIdOperationCompleted;
        
        private System.Threading.SendOrPostCallback createCustomerOrderOperationCompleted;
        
        private System.Threading.SendOrPostCallback calculateOrderPriceOperationCompleted;
        
        private System.Threading.SendOrPostCallback createSteelmeshOrderOperationCompleted;
        
        private System.Threading.SendOrPostCallback queryWipProduceScheduleOperationCompleted;
        
        private System.Threading.SendOrPostCallback createBacktoSingleOrderOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public CustomerOpenService() {
            this.Url = global::Hands.K3.SCM.App.Core.Properties.Settings.Default.JN_K3_Seeed_App_Core_JLCWebService_CustomerOpenService;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event queryOrderDetailsByQcCodeCompletedEventHandler queryOrderDetailsByQcCodeCompleted;
        
        /// <remarks/>
        public event queryOrderInfoByIdCompletedEventHandler queryOrderInfoByIdCompleted;
        
        /// <remarks/>
        public event createCustomerOrderCompletedEventHandler createCustomerOrderCompleted;
        
        /// <remarks/>
        public event calculateOrderPriceCompletedEventHandler calculateOrderPriceCompleted;
        
        /// <remarks/>
        public event createSteelmeshOrderCompletedEventHandler createSteelmeshOrderCompleted;
        
        /// <remarks/>
        public event queryWipProduceScheduleCompletedEventHandler queryWipProduceScheduleCompleted;
        
        /// <remarks/>
        public event createBacktoSingleOrderCompletedEventHandler createBacktoSingleOrderCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="http://webservice.product.gordian.com", ResponseNamespace="http://webservice.product.gordian.com", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("out", IsNullable=true)]
        public string queryOrderDetailsByQcCode([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string in0, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string in1, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] System.Nullable<int> in2, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string in3, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string in4) {
            object[] results = this.Invoke("queryOrderDetailsByQcCode", new object[] {
                        in0,
                        in1,
                        in2,
                        in3,
                        in4});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void queryOrderDetailsByQcCodeAsync(string in0, string in1, System.Nullable<int> in2, string in3, string in4) {
            this.queryOrderDetailsByQcCodeAsync(in0, in1, in2, in3, in4, null);
        }
        
        /// <remarks/>
        public void queryOrderDetailsByQcCodeAsync(string in0, string in1, System.Nullable<int> in2, string in3, string in4, object userState) {
            if ((this.queryOrderDetailsByQcCodeOperationCompleted == null)) {
                this.queryOrderDetailsByQcCodeOperationCompleted = new System.Threading.SendOrPostCallback(this.OnqueryOrderDetailsByQcCodeOperationCompleted);
            }
            this.InvokeAsync("queryOrderDetailsByQcCode", new object[] {
                        in0,
                        in1,
                        in2,
                        in3,
                        in4}, this.queryOrderDetailsByQcCodeOperationCompleted, userState);
        }
        
        private void OnqueryOrderDetailsByQcCodeOperationCompleted(object arg) {
            if ((this.queryOrderDetailsByQcCodeCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.queryOrderDetailsByQcCodeCompleted(this, new queryOrderDetailsByQcCodeCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="http://webservice.product.gordian.com", ResponseNamespace="http://webservice.product.gordian.com", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("out", IsNullable=true)]
        public string queryOrderInfoById([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string in0, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string in1, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string in2, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] System.Nullable<int> in3) {
            object[] results = this.Invoke("queryOrderInfoById", new object[] {
                        in0,
                        in1,
                        in2,
                        in3});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void queryOrderInfoByIdAsync(string in0, string in1, string in2, System.Nullable<int> in3) {
            this.queryOrderInfoByIdAsync(in0, in1, in2, in3, null);
        }
        
        /// <remarks/>
        public void queryOrderInfoByIdAsync(string in0, string in1, string in2, System.Nullable<int> in3, object userState) {
            if ((this.queryOrderInfoByIdOperationCompleted == null)) {
                this.queryOrderInfoByIdOperationCompleted = new System.Threading.SendOrPostCallback(this.OnqueryOrderInfoByIdOperationCompleted);
            }
            this.InvokeAsync("queryOrderInfoById", new object[] {
                        in0,
                        in1,
                        in2,
                        in3}, this.queryOrderInfoByIdOperationCompleted, userState);
        }
        
        private void OnqueryOrderInfoByIdOperationCompleted(object arg) {
            if ((this.queryOrderInfoByIdCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.queryOrderInfoByIdCompleted(this, new queryOrderInfoByIdCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="http://webservice.product.gordian.com", ResponseNamespace="http://webservice.product.gordian.com", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("out", IsNullable=true)]
        public string createCustomerOrder([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string in0, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string in1, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string in2, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string in3, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string in4) {
            object[] results = this.Invoke("createCustomerOrder", new object[] {
                        in0,
                        in1,
                        in2,
                        in3,
                        in4});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void createCustomerOrderAsync(string in0, string in1, string in2, string in3, string in4) {
            this.createCustomerOrderAsync(in0, in1, in2, in3, in4, null);
        }
        
        /// <remarks/>
        public void createCustomerOrderAsync(string in0, string in1, string in2, string in3, string in4, object userState) {
            if ((this.createCustomerOrderOperationCompleted == null)) {
                this.createCustomerOrderOperationCompleted = new System.Threading.SendOrPostCallback(this.OncreateCustomerOrderOperationCompleted);
            }
            this.InvokeAsync("createCustomerOrder", new object[] {
                        in0,
                        in1,
                        in2,
                        in3,
                        in4}, this.createCustomerOrderOperationCompleted, userState);
        }
        
        private void OncreateCustomerOrderOperationCompleted(object arg) {
            if ((this.createCustomerOrderCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.createCustomerOrderCompleted(this, new createCustomerOrderCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="http://webservice.product.gordian.com", ResponseNamespace="http://webservice.product.gordian.com", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("out", IsNullable=true)]
        public string calculateOrderPrice([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string in0, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string in1, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string in2) {
            object[] results = this.Invoke("calculateOrderPrice", new object[] {
                        in0,
                        in1,
                        in2});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void calculateOrderPriceAsync(string in0, string in1, string in2) {
            this.calculateOrderPriceAsync(in0, in1, in2, null);
        }
        
        /// <remarks/>
        public void calculateOrderPriceAsync(string in0, string in1, string in2, object userState) {
            if ((this.calculateOrderPriceOperationCompleted == null)) {
                this.calculateOrderPriceOperationCompleted = new System.Threading.SendOrPostCallback(this.OncalculateOrderPriceOperationCompleted);
            }
            this.InvokeAsync("calculateOrderPrice", new object[] {
                        in0,
                        in1,
                        in2}, this.calculateOrderPriceOperationCompleted, userState);
        }
        
        private void OncalculateOrderPriceOperationCompleted(object arg) {
            if ((this.calculateOrderPriceCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.calculateOrderPriceCompleted(this, new calculateOrderPriceCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="http://webservice.product.gordian.com", ResponseNamespace="http://webservice.product.gordian.com", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("out", IsNullable=true)]
        public string createSteelmeshOrder([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string in0, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string in1, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string in2, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string in3, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string in4) {
            object[] results = this.Invoke("createSteelmeshOrder", new object[] {
                        in0,
                        in1,
                        in2,
                        in3,
                        in4});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void createSteelmeshOrderAsync(string in0, string in1, string in2, string in3, string in4) {
            this.createSteelmeshOrderAsync(in0, in1, in2, in3, in4, null);
        }
        
        /// <remarks/>
        public void createSteelmeshOrderAsync(string in0, string in1, string in2, string in3, string in4, object userState) {
            if ((this.createSteelmeshOrderOperationCompleted == null)) {
                this.createSteelmeshOrderOperationCompleted = new System.Threading.SendOrPostCallback(this.OncreateSteelmeshOrderOperationCompleted);
            }
            this.InvokeAsync("createSteelmeshOrder", new object[] {
                        in0,
                        in1,
                        in2,
                        in3,
                        in4}, this.createSteelmeshOrderOperationCompleted, userState);
        }
        
        private void OncreateSteelmeshOrderOperationCompleted(object arg) {
            if ((this.createSteelmeshOrderCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.createSteelmeshOrderCompleted(this, new createSteelmeshOrderCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="http://webservice.product.gordian.com", ResponseNamespace="http://webservice.product.gordian.com", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("out", IsNullable=true)]
        public string queryWipProduceSchedule([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string in0, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string in1, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] System.Nullable<int> in2, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string in3) {
            object[] results = this.Invoke("queryWipProduceSchedule", new object[] {
                        in0,
                        in1,
                        in2,
                        in3});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void queryWipProduceScheduleAsync(string in0, string in1, System.Nullable<int> in2, string in3) {
            this.queryWipProduceScheduleAsync(in0, in1, in2, in3, null);
        }
        
        /// <remarks/>
        public void queryWipProduceScheduleAsync(string in0, string in1, System.Nullable<int> in2, string in3, object userState) {
            if ((this.queryWipProduceScheduleOperationCompleted == null)) {
                this.queryWipProduceScheduleOperationCompleted = new System.Threading.SendOrPostCallback(this.OnqueryWipProduceScheduleOperationCompleted);
            }
            this.InvokeAsync("queryWipProduceSchedule", new object[] {
                        in0,
                        in1,
                        in2,
                        in3}, this.queryWipProduceScheduleOperationCompleted, userState);
        }
        
        private void OnqueryWipProduceScheduleOperationCompleted(object arg) {
            if ((this.queryWipProduceScheduleCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.queryWipProduceScheduleCompleted(this, new queryWipProduceScheduleCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="http://webservice.product.gordian.com", ResponseNamespace="http://webservice.product.gordian.com", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("out", IsNullable=true)]
        public string createBacktoSingleOrder([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string in0, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string in1, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string in2, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string in3, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string in4) {
            object[] results = this.Invoke("createBacktoSingleOrder", new object[] {
                        in0,
                        in1,
                        in2,
                        in3,
                        in4});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void createBacktoSingleOrderAsync(string in0, string in1, string in2, string in3, string in4) {
            this.createBacktoSingleOrderAsync(in0, in1, in2, in3, in4, null);
        }
        
        /// <remarks/>
        public void createBacktoSingleOrderAsync(string in0, string in1, string in2, string in3, string in4, object userState) {
            if ((this.createBacktoSingleOrderOperationCompleted == null)) {
                this.createBacktoSingleOrderOperationCompleted = new System.Threading.SendOrPostCallback(this.OncreateBacktoSingleOrderOperationCompleted);
            }
            this.InvokeAsync("createBacktoSingleOrder", new object[] {
                        in0,
                        in1,
                        in2,
                        in3,
                        in4}, this.createBacktoSingleOrderOperationCompleted, userState);
        }
        
        private void OncreateBacktoSingleOrderOperationCompleted(object arg) {
            if ((this.createBacktoSingleOrderCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.createBacktoSingleOrderCompleted(this, new createBacktoSingleOrderCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2558.0")]
    public delegate void queryOrderDetailsByQcCodeCompletedEventHandler(object sender, queryOrderDetailsByQcCodeCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2558.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class queryOrderDetailsByQcCodeCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal queryOrderDetailsByQcCodeCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2558.0")]
    public delegate void queryOrderInfoByIdCompletedEventHandler(object sender, queryOrderInfoByIdCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2558.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class queryOrderInfoByIdCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal queryOrderInfoByIdCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2558.0")]
    public delegate void createCustomerOrderCompletedEventHandler(object sender, createCustomerOrderCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2558.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class createCustomerOrderCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal createCustomerOrderCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2558.0")]
    public delegate void calculateOrderPriceCompletedEventHandler(object sender, calculateOrderPriceCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2558.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class calculateOrderPriceCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal calculateOrderPriceCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2558.0")]
    public delegate void createSteelmeshOrderCompletedEventHandler(object sender, createSteelmeshOrderCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2558.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class createSteelmeshOrderCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal createSteelmeshOrderCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2558.0")]
    public delegate void queryWipProduceScheduleCompletedEventHandler(object sender, queryWipProduceScheduleCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2558.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class queryWipProduceScheduleCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal queryWipProduceScheduleCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2558.0")]
    public delegate void createBacktoSingleOrderCompletedEventHandler(object sender, createBacktoSingleOrderCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2558.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class createBacktoSingleOrderCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal createBacktoSingleOrderCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591