//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

// 
// 此源代码是由 Microsoft.VSDesigner 4.0.30319.42000 版自动生成。
// 
#pragma warning disable 1591

namespace Hands.K3.SCM.App.Core.UpdatePlmSkuStatus {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    // CODEGEN: 未处理命名空间“http://schemas.microsoft.com/soap-toolkit/wsdl-extension”中的可选 WSDL 扩展元素“binding”。
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2558.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="SoapBinding", Namespace="http://www.ptc.com/infoengine/soap/rpc/message/")]
    public partial class IESoapServlet : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback setWTPartlifecycleOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public IESoapServlet() {
            this.Url = global::Hands.K3.SCM.App.Core.Properties.Settings.Default.JN_K3_Seeed_App_Core_UpdatePlmSkuStatus_IESoapServlet;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event setWTPartlifecycleCompletedEventHandler setWTPartlifecycleCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("urn:ie-soap-rpc:ext.cust!setWTPartlifecycle", RequestNamespace="http://www.ptc.com/infoengine/soap/rpc/message/", ResponseNamespace="http://www.ptc.com/infoengine/soap/rpc/message/")]
        [return: System.Xml.Serialization.SoapElementAttribute("Collection")]
        public string setWTPartlifecycle(string partNumber) {
            object[] results = this.Invoke("setWTPartlifecycle", new object[] {
                        partNumber});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void setWTPartlifecycleAsync(string partNumber) {
            this.setWTPartlifecycleAsync(partNumber, null);
        }
        
        /// <remarks/>
        public void setWTPartlifecycleAsync(string partNumber, object userState) {
            if ((this.setWTPartlifecycleOperationCompleted == null)) {
                this.setWTPartlifecycleOperationCompleted = new System.Threading.SendOrPostCallback(this.OnsetWTPartlifecycleOperationCompleted);
            }
            this.InvokeAsync("setWTPartlifecycle", new object[] {
                        partNumber}, this.setWTPartlifecycleOperationCompleted, userState);
        }
        
        private void OnsetWTPartlifecycleOperationCompleted(object arg) {
            if ((this.setWTPartlifecycleCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.setWTPartlifecycleCompleted(this, new setWTPartlifecycleCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2558.0")]
    public delegate void setWTPartlifecycleCompletedEventHandler(object sender, setWTPartlifecycleCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2558.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class setWTPartlifecycleCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal setWTPartlifecycleCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591