//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

// 
// 此源代码是由 Microsoft.VSDesigner 4.0.30319.42000 版自动生成。
// 
#pragma warning disable 1591

namespace Hands.K3.SCM.App.Core.BHProductWebService {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2558.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="ServiceForProductSOAP", Namespace="http://www.example.org/ServiceForProduct/")]
    public partial class ServiceForProduct : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback createProductOperationCompleted;
        
        private System.Threading.SendOrPostCallback getStockOperationCompleted;
        
        private System.Threading.SendOrPostCallback getProductOperationCompleted;
        
        private System.Threading.SendOrPostCallback getBatchStockOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public ServiceForProduct() {
            this.Url = global::Hands.K3.SCM.App.Core.Properties.Settings.Default.JN_K3_Seeed_App_Core_BHProductWebService_ServiceForProduct;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event createProductCompletedEventHandler createProductCompleted;
        
        /// <remarks/>
        public event getStockCompletedEventHandler getStockCompleted;
        
        /// <remarks/>
        public event getProductCompletedEventHandler getProductCompleted;
        
        /// <remarks/>
        public event getBatchStockCompletedEventHandler getBatchStockCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.example.org/ServiceForProduct/createProduct", RequestNamespace="http://www.example.org/ServiceForProduct/", ResponseNamespace="http://www.example.org/ServiceForProduct/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("ask", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string createProduct([System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] HeaderRequest HeaderRequest, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] ProductInfo ProductInfo, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] out string message, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] out string skuNo, [System.Xml.Serialization.XmlElementAttribute("error", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] out errorType[] error, [System.Xml.Serialization.XmlElementAttribute("errorCodeMsg", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] out errorCodeMsgType[] errorCodeMsg) {
            object[] results = this.Invoke("createProduct", new object[] {
                        HeaderRequest,
                        ProductInfo});
            message = ((string)(results[1]));
            skuNo = ((string)(results[2]));
            error = ((errorType[])(results[3]));
            errorCodeMsg = ((errorCodeMsgType[])(results[4]));
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void createProductAsync(HeaderRequest HeaderRequest, ProductInfo ProductInfo) {
            this.createProductAsync(HeaderRequest, ProductInfo, null);
        }
        
        /// <remarks/>
        public void createProductAsync(HeaderRequest HeaderRequest, ProductInfo ProductInfo, object userState) {
            if ((this.createProductOperationCompleted == null)) {
                this.createProductOperationCompleted = new System.Threading.SendOrPostCallback(this.OncreateProductOperationCompleted);
            }
            this.InvokeAsync("createProduct", new object[] {
                        HeaderRequest,
                        ProductInfo}, this.createProductOperationCompleted, userState);
        }
        
        private void OncreateProductOperationCompleted(object arg) {
            if ((this.createProductCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.createProductCompleted(this, new createProductCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.example.org/ServiceForProduct/getStock", RequestNamespace="http://www.example.org/ServiceForProduct/", ResponseNamespace="http://www.example.org/ServiceForProduct/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("ask", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string getStock([System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] HeaderRequest HeaderRequest, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string skuNo, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] out string message, [System.Xml.Serialization.XmlElementAttribute("data", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] out inventoryRow[] data, [System.Xml.Serialization.XmlElementAttribute("errorCodeMsg", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] out errorCodeMsgType[] errorCodeMsg) {
            object[] results = this.Invoke("getStock", new object[] {
                        HeaderRequest,
                        skuNo});
            message = ((string)(results[1]));
            data = ((inventoryRow[])(results[2]));
            errorCodeMsg = ((errorCodeMsgType[])(results[3]));
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void getStockAsync(HeaderRequest HeaderRequest, string skuNo) {
            this.getStockAsync(HeaderRequest, skuNo, null);
        }
        
        /// <remarks/>
        public void getStockAsync(HeaderRequest HeaderRequest, string skuNo, object userState) {
            if ((this.getStockOperationCompleted == null)) {
                this.getStockOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetStockOperationCompleted);
            }
            this.InvokeAsync("getStock", new object[] {
                        HeaderRequest,
                        skuNo}, this.getStockOperationCompleted, userState);
        }
        
        private void OngetStockOperationCompleted(object arg) {
            if ((this.getStockCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.getStockCompleted(this, new getStockCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.example.org/ServiceForProduct/getProduct", RequestNamespace="http://www.example.org/ServiceForProduct/", ResponseNamespace="http://www.example.org/ServiceForProduct/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("ask", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string getProduct([System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] HeaderRequest HeaderRequest, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string skuNo, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] out string message, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] out productRow data, [System.Xml.Serialization.XmlElementAttribute("errorCodeMsg", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] out errorCodeMsgType[] errorCodeMsg) {
            object[] results = this.Invoke("getProduct", new object[] {
                        HeaderRequest,
                        skuNo});
            message = ((string)(results[1]));
            data = ((productRow)(results[2]));
            errorCodeMsg = ((errorCodeMsgType[])(results[3]));
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void getProductAsync(HeaderRequest HeaderRequest, string skuNo) {
            this.getProductAsync(HeaderRequest, skuNo, null);
        }
        
        /// <remarks/>
        public void getProductAsync(HeaderRequest HeaderRequest, string skuNo, object userState) {
            if ((this.getProductOperationCompleted == null)) {
                this.getProductOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetProductOperationCompleted);
            }
            this.InvokeAsync("getProduct", new object[] {
                        HeaderRequest,
                        skuNo}, this.getProductOperationCompleted, userState);
        }
        
        private void OngetProductOperationCompleted(object arg) {
            if ((this.getProductCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.getProductCompleted(this, new getProductCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.example.org/ServiceForProduct/getBatchStock", RequestNamespace="http://www.example.org/ServiceForProduct/", ResponseNamespace="http://www.example.org/ServiceForProduct/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("ask", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string getBatchStock([System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] HeaderRequest HeaderRequest, [System.Xml.Serialization.XmlElementAttribute("skuNoArr", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string[] skuNoArr, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] out string message, [System.Xml.Serialization.XmlElementAttribute("error", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] out string[] error, [System.Xml.Serialization.XmlElementAttribute("data", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] out inventoryRow[] data, [System.Xml.Serialization.XmlElementAttribute("errorCodeMsg", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] out errorCodeMsgType[] errorCodeMsg) {
            object[] results = this.Invoke("getBatchStock", new object[] {
                        HeaderRequest,
                        skuNoArr});
            message = ((string)(results[1]));
            error = ((string[])(results[2]));
            data = ((inventoryRow[])(results[3]));
            errorCodeMsg = ((errorCodeMsgType[])(results[4]));
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void getBatchStockAsync(HeaderRequest HeaderRequest, string[] skuNoArr) {
            this.getBatchStockAsync(HeaderRequest, skuNoArr, null);
        }
        
        /// <remarks/>
        public void getBatchStockAsync(HeaderRequest HeaderRequest, string[] skuNoArr, object userState) {
            if ((this.getBatchStockOperationCompleted == null)) {
                this.getBatchStockOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetBatchStockOperationCompleted);
            }
            this.InvokeAsync("getBatchStock", new object[] {
                        HeaderRequest,
                        skuNoArr}, this.getBatchStockOperationCompleted, userState);
        }
        
        private void OngetBatchStockOperationCompleted(object arg) {
            if ((this.getBatchStockCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.getBatchStockCompleted(this, new getBatchStockCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.example.org/ServiceForProduct/")]
    public partial class HeaderRequest {
        
        private string customerCodeField;
        
        private string operationCustomerCodeField;
        
        private string appTokenField;
        
        private string appKeyField;
        
        private string versionField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string customerCode {
            get {
                return this.customerCodeField;
            }
            set {
                this.customerCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string operationCustomerCode {
            get {
                return this.operationCustomerCodeField;
            }
            set {
                this.operationCustomerCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string appToken {
            get {
                return this.appTokenField;
            }
            set {
                this.appTokenField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string appKey {
            get {
                return this.appKeyField;
            }
            set {
                this.appKeyField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string version {
            get {
                return this.versionField;
            }
            set {
                this.versionField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.example.org/ServiceForProduct/")]
    public partial class productRow {
        
        private string goods_idField;
        
        private string product_skuField;
        
        private string product_barcodeField;
        
        private string product_titleField;
        
        private string product_title_enField;
        
        private string product_statusField;
        
        private string hs_goods_nameField;
        
        private string hs_codeField;
        
        private string product_weightField;
        
        private string product_declared_valueField;
        
        private string is_accessoriesField;
        
        private string has_invoiceField;
        
        private string currency_codeField;
        
        private string model_serialField;
        
        private string model_serial2Field;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string goods_id {
            get {
                return this.goods_idField;
            }
            set {
                this.goods_idField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string product_sku {
            get {
                return this.product_skuField;
            }
            set {
                this.product_skuField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string product_barcode {
            get {
                return this.product_barcodeField;
            }
            set {
                this.product_barcodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string product_title {
            get {
                return this.product_titleField;
            }
            set {
                this.product_titleField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string product_title_en {
            get {
                return this.product_title_enField;
            }
            set {
                this.product_title_enField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string product_status {
            get {
                return this.product_statusField;
            }
            set {
                this.product_statusField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string hs_goods_name {
            get {
                return this.hs_goods_nameField;
            }
            set {
                this.hs_goods_nameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string hs_code {
            get {
                return this.hs_codeField;
            }
            set {
                this.hs_codeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string product_weight {
            get {
                return this.product_weightField;
            }
            set {
                this.product_weightField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string product_declared_value {
            get {
                return this.product_declared_valueField;
            }
            set {
                this.product_declared_valueField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string is_accessories {
            get {
                return this.is_accessoriesField;
            }
            set {
                this.is_accessoriesField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string has_invoice {
            get {
                return this.has_invoiceField;
            }
            set {
                this.has_invoiceField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string currency_code {
            get {
                return this.currency_codeField;
            }
            set {
                this.currency_codeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string model_serial {
            get {
                return this.model_serialField;
            }
            set {
                this.model_serialField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string model_serial2 {
            get {
                return this.model_serial2Field;
            }
            set {
                this.model_serial2Field = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.example.org/ServiceForProduct/")]
    public partial class inventoryRow {
        
        private string skuNoField;
        
        private string warehouseCodeField;
        
        private string onwayQtyField;
        
        private string pendingQtyField;
        
        private string sellableQtyField;
        
        private string unsellableQtyField;
        
        private string reservedQtyField;
        
        private string shippedQtyField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string skuNo {
            get {
                return this.skuNoField;
            }
            set {
                this.skuNoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string warehouseCode {
            get {
                return this.warehouseCodeField;
            }
            set {
                this.warehouseCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string onwayQty {
            get {
                return this.onwayQtyField;
            }
            set {
                this.onwayQtyField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string pendingQty {
            get {
                return this.pendingQtyField;
            }
            set {
                this.pendingQtyField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string sellableQty {
            get {
                return this.sellableQtyField;
            }
            set {
                this.sellableQtyField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string unsellableQty {
            get {
                return this.unsellableQtyField;
            }
            set {
                this.unsellableQtyField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string reservedQty {
            get {
                return this.reservedQtyField;
            }
            set {
                this.reservedQtyField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string shippedQty {
            get {
                return this.shippedQtyField;
            }
            set {
                this.shippedQtyField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.example.org/ServiceForProduct/")]
    public partial class errorCodeMsgType {
        
        private string codeField;
        
        private string msgField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string code {
            get {
                return this.codeField;
            }
            set {
                this.codeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string msg {
            get {
                return this.msgField;
            }
            set {
                this.msgField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.example.org/ServiceForProduct/")]
    public partial class errorType {
        
        private string errorMessageField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string errorMessage {
            get {
                return this.errorMessageField;
            }
            set {
                this.errorMessageField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.example.org/ServiceForProduct/")]
    public partial class ProductInfo {
        
        private string skuNoField;
        
        private string skuNameField;
        
        private string productTtitleEnField;
        
        private int barcodeTypeField;
        
        private string barcodeDefineField;
        
        private float productDeclaredValueField;
        
        private string weightField;
        
        private string hasInvoiceField;
        
        private string is_accessoriesField;
        
        private string hsGoodsNameField;
        
        private string hsCodeField;
        
        private string uOMField;
        
        private string recordInfoField;
        
        private string isRecordField;
        
        private string with_batteryField;
        
        private string battery_typeField;
        
        private string battery_detailField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string skuNo {
            get {
                return this.skuNoField;
            }
            set {
                this.skuNoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string skuName {
            get {
                return this.skuNameField;
            }
            set {
                this.skuNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string productTtitleEn {
            get {
                return this.productTtitleEnField;
            }
            set {
                this.productTtitleEnField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int barcodeType {
            get {
                return this.barcodeTypeField;
            }
            set {
                this.barcodeTypeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string barcodeDefine {
            get {
                return this.barcodeDefineField;
            }
            set {
                this.barcodeDefineField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public float productDeclaredValue {
            get {
                return this.productDeclaredValueField;
            }
            set {
                this.productDeclaredValueField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string weight {
            get {
                return this.weightField;
            }
            set {
                this.weightField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string hasInvoice {
            get {
                return this.hasInvoiceField;
            }
            set {
                this.hasInvoiceField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string is_accessories {
            get {
                return this.is_accessoriesField;
            }
            set {
                this.is_accessoriesField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string hsGoodsName {
            get {
                return this.hsGoodsNameField;
            }
            set {
                this.hsGoodsNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string hsCode {
            get {
                return this.hsCodeField;
            }
            set {
                this.hsCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string UOM {
            get {
                return this.uOMField;
            }
            set {
                this.uOMField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string recordInfo {
            get {
                return this.recordInfoField;
            }
            set {
                this.recordInfoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string isRecord {
            get {
                return this.isRecordField;
            }
            set {
                this.isRecordField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string with_battery {
            get {
                return this.with_batteryField;
            }
            set {
                this.with_batteryField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string battery_type {
            get {
                return this.battery_typeField;
            }
            set {
                this.battery_typeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string battery_detail {
            get {
                return this.battery_detailField;
            }
            set {
                this.battery_detailField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2558.0")]
    public delegate void createProductCompletedEventHandler(object sender, createProductCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2558.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class createProductCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal createProductCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
        
        /// <remarks/>
        public string message {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[1]));
            }
        }
        
        /// <remarks/>
        public string skuNo {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[2]));
            }
        }
        
        /// <remarks/>
        public errorType[] error {
            get {
                this.RaiseExceptionIfNecessary();
                return ((errorType[])(this.results[3]));
            }
        }
        
        /// <remarks/>
        public errorCodeMsgType[] errorCodeMsg {
            get {
                this.RaiseExceptionIfNecessary();
                return ((errorCodeMsgType[])(this.results[4]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2558.0")]
    public delegate void getStockCompletedEventHandler(object sender, getStockCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2558.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class getStockCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal getStockCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
        
        /// <remarks/>
        public string message {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[1]));
            }
        }
        
        /// <remarks/>
        public inventoryRow[] data {
            get {
                this.RaiseExceptionIfNecessary();
                return ((inventoryRow[])(this.results[2]));
            }
        }
        
        /// <remarks/>
        public errorCodeMsgType[] errorCodeMsg {
            get {
                this.RaiseExceptionIfNecessary();
                return ((errorCodeMsgType[])(this.results[3]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2558.0")]
    public delegate void getProductCompletedEventHandler(object sender, getProductCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2558.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class getProductCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal getProductCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
        
        /// <remarks/>
        public string message {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[1]));
            }
        }
        
        /// <remarks/>
        public productRow data {
            get {
                this.RaiseExceptionIfNecessary();
                return ((productRow)(this.results[2]));
            }
        }
        
        /// <remarks/>
        public errorCodeMsgType[] errorCodeMsg {
            get {
                this.RaiseExceptionIfNecessary();
                return ((errorCodeMsgType[])(this.results[3]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2558.0")]
    public delegate void getBatchStockCompletedEventHandler(object sender, getBatchStockCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2558.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class getBatchStockCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal getBatchStockCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
        
        /// <remarks/>
        public string message {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[1]));
            }
        }
        
        /// <remarks/>
        public string[] error {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string[])(this.results[2]));
            }
        }
        
        /// <remarks/>
        public inventoryRow[] data {
            get {
                this.RaiseExceptionIfNecessary();
                return ((inventoryRow[])(this.results[3]));
            }
        }
        
        /// <remarks/>
        public errorCodeMsgType[] errorCodeMsg {
            get {
                this.RaiseExceptionIfNecessary();
                return ((errorCodeMsgType[])(this.results[4]));
            }
        }
    }
}

#pragma warning restore 1591