//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hands.K3.SCM.App.Core.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "15.9.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://test.sz-jlc.com/xfire/CustomerOpenService")]
        public string JN_K3_Hans_App_Core_JLCWebService_CustomerOpenService {
            get {
                return ((string)(this["JN_K3_Hans_App_Core_JLCWebService_CustomerOpenService"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://api.4px.com:8058/OrderOnline/ws/OrderOnlineService.dll")]
        public string JN_K3_Hans_App_Core_FourPXWebService_OrderOnlineServiceImplService {
            get {
                return ((string)(this["JN_K3_Hans_App_Core_FourPXWebService_OrderOnlineServiceImplService"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://stu-plm.com:80/Windchill/servlet/DrawingService")]
        public string JN_K3_Hans_App_Core_PLMDrawingWebService_DrawingService {
            get {
                return ((string)(this["JN_K3_Hans_App_Core_PLMDrawingWebService_DrawingService"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://exoms.globex.cn/default/order-soap/web-service")]
        public string JN_K3_Hans_App_Core_BHOrderWebService_ServiceForOrder {
            get {
                return ((string)(this["JN_K3_Hans_App_Core_BHOrderWebService_ServiceForOrder"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://exoms.globex.cn/default/product-soap/web-service")]
        public string JN_K3_Hans_App_Core_BHProductService_ServiceForProduct {
            get {
                return ((string)(this["JN_K3_Hans_App_Core_BHProductService_ServiceForProduct"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://plm.Hansstudio.com.cn/Windchill/servlet/ECNService")]
        public string JN_K3_Hans_App_Core_UpdatePLMECNStatus_ECNService {
            get {
                return ((string)(this["JN_K3_Hans_App_Core_UpdatePLMECNStatus_ECNService"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://dx.sz-jlc.com/xfire/CustomerOpenService")]
        public string JN_K3_Hans_App_Core_JLCWebService_zs_CustomerOpenService {
            get {
                return ((string)(this["JN_K3_Hans_App_Core_JLCWebService_zs_CustomerOpenService"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://plm.Hansstudio.com.cn/Windchill/servlet/RPC")]
        public string JN_K3_Hans_App_Core_UpdatePlmSkuStatus_IESoapServlet {
            get {
                return ((string)(this["JN_K3_Hans_App_Core_UpdatePlmSkuStatus_IESoapServlet"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://exoms.globex.cn/default/product-soap/web-service")]
        public string JN_K3_Hans_App_Core_BHProductWebService_ServiceForProduct {
            get {
                return ((string)(this["JN_K3_Hans_App_Core_BHProductWebService_ServiceForProduct"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://exoms.globex.cn/default/order-soap/web-service")]
        public string JN_K3_Seeed_App_Core_BHOrderWebService_ServiceForOrder {
            get {
                return ((string)(this["JN_K3_Seeed_App_Core_BHOrderWebService_ServiceForOrder"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://exoms.globex.cn/default/product-soap/web-service")]
        public string JN_K3_Seeed_App_Core_BHProductWebService_ServiceForProduct {
            get {
                return ((string)(this["JN_K3_Seeed_App_Core_BHProductWebService_ServiceForProduct"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://api.4px.com:8058/OrderOnline/ws/OrderOnlineService.dll")]
        public string JN_K3_Seeed_App_Core_FourPXWebService_OrderOnlineServiceImplService {
            get {
                return ((string)(this["JN_K3_Seeed_App_Core_FourPXWebService_OrderOnlineServiceImplService"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://test.sz-jlc.com/xfire/CustomerOpenService")]
        public string JN_K3_Seeed_App_Core_JLCWebService_CustomerOpenService {
            get {
                return ((string)(this["JN_K3_Seeed_App_Core_JLCWebService_CustomerOpenService"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://192.168.1.36:80/Windchill/servlet/ECNService")]
        public string JN_K3_Seeed_App_Core_UpdatePLMECNStatus_ECNService {
            get {
                return ((string)(this["JN_K3_Seeed_App_Core_UpdatePLMECNStatus_ECNService"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://stu-plm.com/Windchill/servlet/RPC")]
        public string JN_K3_Seeed_App_Core_UpdatePlmSkuStatus_IESoapServlet {
            get {
                return ((string)(this["JN_K3_Seeed_App_Core_UpdatePlmSkuStatus_IESoapServlet"]));
            }
        }
    }
}
